### ISSUE TITLE
求教：如何在网页端播放英语

### ISSUE THREAD

**Issue by Chengyuanyue** [justorez/peppa#3]
您的项目对我非常有用，非常感谢开源分享！最近我收集了一些英语单词，也想尝试制作MP3音频，方便自己边走边听，我很好奇是如何在网页端实现音频播放的？谢谢！

**Comment by justorez** [comment]
这个项目里的音频播放不是mp3，是实时的文字转语音。

浏览器有语音API：https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API#speech_synthesis
也可以直接看项目的代码实现：https://github.com/justorez/peppa/blob/main/src/composables/episode.ts#L78

不过手机上的大部分国产浏览器不支持这个功能，如果想在手机上用，建议安装手机chrome最新版本。

**Comment by Chengyuanyue** [comment]
非常感谢您的解答，这对我非常有帮助！
